language: ruby

rvm:
  - 2.7.0

bundler_args: --without production

cache: bundler

services:
  - mysql

before_script:
  - cp config/database.yml
  - ./bin/rails db:create
  - ./bin/rails db:migrate
