dist: trusty
language: ruby
rvm:
  - 2.7.0
bundler_args: --without production
cache: bundler
services:
  - docker
  - mysql
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rails db:migrate RAILS_ENV=test
